### ISSUE TITLE
RSS解析时出现 SAXParseException is not JSON serializable

### ISSUE THREAD

**Issue by lunzima** [Quan666/ELF_RSS#145]
使用的版本是Release 2.2.6

> 06-28 10:40:10 [INFO] nonebot | 狼叔WolF 检查更新
06-28 10:40:10 [ERROR] apscheduler | Job "check_update (trigger: interval[0:01:00], next run at: 2021-06-28 10:41:15 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "lzmbot/plugins/rss/RSS/util.py", line 13, in wrapper
    return await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "lzmbot/plugins/rss/RSS/my_trigger.py", line 16, in check_update
    await rss_parsing.start(rss)
  File "lzmbot/plugins/rss/RSS/rss_parsing.py", line 91, in start
    write_rss(name=rss.name, new_rss=new_rss)
  File "lzmbot/plugins/rss/RSS/rss_parsing.py", line 871, in write_rss
    dump_f.write(json.dumps(old, sort_keys=True, indent=4, ensure_ascii=False))
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SAXParseException is not JSON serializable

**Comment by lunzima** [comment]
之后第二次检查RSS时则出现

> 
06-28 10:45:45 [ERROR] apscheduler | Job "check_update (trigger: interval[0:01:00], next run at: 2021-06-28 10:46:51 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 26, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 386, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/dist-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "lzmbot/plugins/rss/RSS/util.py", line 13, in wrapper
    return await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "lzmbot/plugins/rss/RSS/my_trigger.py", line 16, in check_update
    await rss_parsing.start(rss)
  File "lzmbot/plugins/rss/RSS/rss_parsing.py", line 89, in start
    old_rss_list = read_rss(rss.name).get("entries")
  File "lzmbot/plugins/rss/RSS/rss_parsing.py", line 849, in read_rss
    load_dict = json.load(load_f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by NekoAria** [comment]
能把你的这个订阅的地址发一下吗？
这个情况是由于订阅没内容导致的。
不过也确实应该改一下处理逻辑。

**Comment by lunzima** [comment]
感谢修复
