### ISSUE TITLE
群内订阅可以正常使用，change qun=群号无法正常推送

### ISSUE THREAD

**Issue by xiaobaozi233** [Quan666/ELF_RSS#217]
发现只有在群内add可以正常使用，后面私聊change的都无法正常推送，看go那边也没发送群的那份。

![@(FV)@9V5`UZEB R35{KSDS](https://user-images.githubusercontent.com/68990805/139362823-7764aaaa-f55b-4a48-bf24-90a73b28ac57.png)

![4{FLP(L0@IZ08NIX$RDL U6](https://user-images.githubusercontent.com/68990805/139362737-f0d6a50e-686e-4dca-8fb1-63dfbff28228.png)

![LQC`{UET5OD%%RO}YVDHA8T](https://user-images.githubusercontent.com/68990805/139362754-e39b97a5-5614-4f01-8b62-d83503f95c40.png)

**Comment by Quan666** [comment]
请确保群号正确，bot在群里，且未风控

请提供详细的log

**Comment by xiaobaozi233** [comment]
```Shell
11-02 13:26:48 [ERROR] apscheduler | Job "check_update (trigger: interval[0:05:00], next run at: 2021-11-02 13:31:51 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.9/site-packages/pyquery/pyquery.py", line 57, in fromstring
    result = getattr(etree, meth)(context)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/bin/python3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/bin/python3/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/bin/python3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/bin/python3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/bin/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/bin/python3/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "src/plugins/ELF_RSS2/RSS/util.py", line 13, in wrapper
    return await asyncio.wait_for(
  File "/usr/local/bin/python3/lib/python3.9/asyncio/tasks.py", line 478, in wait_for
    return fut.result()
  File "src/plugins/ELF_RSS2/RSS/my_trigger.py", line 16, in check_update
    await rss_parsing.start(rss)
  File "src/plugins/ELF_RSS2/RSS/rss_parsing.py", line 71, in start
    await pr.start(rss_name=rss.name, new_rss=new_rss)
  File "src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 221, in start
    tmp = await handler.func(
  File "src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 385, in handle_summary
    tmp += await handle_html_tag(html=Pq(get_summary(item)))
  File "/usr/local/bin/python3/lib/python3.9/site-packages/pyquery/pyquery.py", line 217, in __init__
    elements = fromstring(context, self.parser)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/pyquery/pyquery.py", line 61, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/lxml/html/__init__.py", line 763, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty
```

刚发现报错是这个，我手动访问rsshub看起来没啥问题。

地址是xueqiu/user/6781224586

**Comment by NekoAria** [comment]
看报错是没正常获取到正文内容，但是我没法复现。
