### ISSUE TITLE
2.0失败，import还是出现问题

### ISSUE THREAD

**Issue by LittleNightmare** [Quan666/ELF_RSS#22]
RSSHUB的import 变成 .RSSHUB，或者. 通过了编译器的检查，但运行时也出现问题，应该是包名问题？

~~`from bot import config` 这个我就不造了~~ 哦，要在bot.py里写一个
`from nonebot import scheduler` 可能是因为我个人的问题？ 我的版本高，nonebot==2.0.0a7，nb-cli应该是3.0

```python
12-16 09:13:30 [ERROR] nonebot | Failed to import "RSSHUB"
Traceback (most recent call last):
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\NoneBot-Plugin-Astrologian\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\handlers.py", line 39, in run_bot
    module = importlib.import_module(module_name)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugins("src/plugins")
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\ELF_RSS2\__init__.py", line 9, in <module>
    _sub_plugins |= nonebot.load_plugins(
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\RSSHUB\__init__.py", line 3, in <module>
    from . import del_cache
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\RSSHUB\del_cache.py", line 2, in <module>
    from bot import config
ImportError: cannot import name 'config' from partially initialized module 'bot' (most likely due to a circular import) (.\bot.py)
12-16 09:13:30 [ERROR] nonebot | Failed to import "add_dy"
Traceback (most recent call last):
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\NoneBot-Plugin-Astrologian\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\handlers.py", line 39, in run_bot
    module = importlib.import_module(module_name)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugins("src/plugins")
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\ELF_RSS2\__init__.py", line 9, in <module>
    _sub_plugins |= nonebot.load_plugins(
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\add_dy.py", line 1, in <module>
    from RSSHUB import RSS_class, RWlist, rsstrigger as TR
ModuleNotFoundError: No module named 'RSSHUB'
12-16 09:13:30 [ERROR] nonebot | Failed to import "change_dy"
Traceback (most recent call last):
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\NoneBot-Plugin-Astrologian\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\handlers.py", line 39, in run_bot
    module = importlib.import_module(module_name)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugins("src/plugins")
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\ELF_RSS2\__init__.py", line 9, in <module>
    _sub_plugins |= nonebot.load_plugins(
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\change_dy.py", line 1, in <module>
    from RSSHUB import rsstrigger as TR, RWlist
ModuleNotFoundError: No module named 'RSSHUB'
12-16 09:13:30 [ERROR] nonebot | Failed to import "del_dy"
Traceback (most recent call last):
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\NoneBot-Plugin-Astrologian\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\handlers.py", line 39, in run_bot
    module = importlib.import_module(module_name)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugins("src/plugins")
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\ELF_RSS2\__init__.py", line 9, in <module>
    _sub_plugins |= nonebot.load_plugins(
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\del_dy.py", line 1, in <module>
    from RSSHUB import RWlist
ModuleNotFoundError: No module named 'RSSHUB'
12-16 09:13:30 [ERROR] nonebot | Failed to import "show_all"
Traceback (most recent call last):
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\NoneBot-Plugin-Astrologian\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\handlers.py", line 39, in run_bot
    module = importlib.import_module(module_name)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugins("src/plugins")
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\ELF_RSS2\__init__.py", line 9, in <module>
    _sub_plugins |= nonebot.load_plugins(
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\show_all.py", line 1, in <module>
    from RSSHUB import RWlist
ModuleNotFoundError: No module named 'RSSHUB'
12-16 09:13:30 [ERROR] nonebot | Failed to import "show_dy"
Traceback (most recent call last):
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\NoneBot-Plugin-Astrologian\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\handlers.py", line 39, in run_bot
    module = importlib.import_module(module_name)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugins("src/plugins")
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\ELF_RSS2\__init__.py", line 9, in <module>
    _sub_plugins |= nonebot.load_plugins(
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\show_dy.py", line 1, in <module>
    from RSSHUB import RWlist
ModuleNotFoundError: No module named 'RSSHUB'
12-16 09:13:30 [ERROR] nonebot | Failed to import "start"
Traceback (most recent call last):
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\NoneBot-Plugin-Astrologian\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\__init__.py", line 46, in run
    run_bot(file, app)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nb_cli\handlers.py", line 39, in run_bot
    module = importlib.import_module(module_name)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 27, in <module>
    nonebot.load_plugins("src/plugins")
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins\ELF_RSS2\__init__.py", line 9, in <module>
    _sub_plugins |= nonebot.load_plugins(
  File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 889, in load_plugins
    result = context.run(_load_plugin, module_info)
> File "d:\anaconda3\envs\nonebot-plugin-astrologian\lib\site-packages\nonebot\plugin.py", line 873, in _load_plugin
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\QQbot\nonebot2_server\src\plugins\ELF_RSS2\plugins\start.py", line 2, in <module>
    from bot import config
ImportError: cannot import name 'config' from partially initialized module 'bot' (most likely due to a circular import) (.\bot.py)
12-16 09:13:30 [INFO] nonebot | Succeeded to import "ELF_RSS2"
12-16 09:13:30 [INFO] nonebot | Running NoneBot...
12-16 09:13:30 [INFO] uvicorn | Started server process [15044]
12-16 09:13:30 [INFO] uvicorn | Waiting for application startup.
12-16 09:13:30 [INFO] uvicorn | Application startup complete.
12-16 09:13:30 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)


```

**Comment by LittleNightmare** [comment]
1. 记得在bot加载`nonebot.load_plugin("nonebot_plugin_apscheduler")`
2. schduler可以参考[apscheduler](https://github.com/nonebot/plugin-apscheduler)
3. 在`\ELF_RSS\src\plugins\ELF_RSS2\__init__.py`里添加`from .plugins import RSSHUB`解决import问题，虽然我的pycharm还在报错，但nb run可以运行
4. 目前会在添加的时候报：
```python
12-16 16:57:02 [INFO] add_dy | E :[Errno 2] No such file or directory: './data/rss.json'
12-16 16:57:02 [INFO] add_dy | 'NoneType' object has no attribute 'add_job'
```
能看见创建，后续重新添加提示已存在，但能不能用，没测试

**Comment by Quan666** [comment]
在准备重写 `add` `change` 命令部分，但还没想到较好的交互方式
import 我还没搞清楚，但原来的方式还是能正常运行 ，使用 `from .plugins import RSSHUB ` 反而不能运行成功
apscheduler 准备不使用 `nonebot_plugin_apscheduler` 插件，准备直接用apscheduler，因为我安装不上
更新了个版本，你试试看 https://github.com/Quan666/ELF_RSS/commit/d9f8eee7edfa22f75305d2e60a37a0e7ff47eb7e
