### ISSUE TITLE
检查更新时apscheduler报错

### ISSUE THREAD

**Issue by YipSzeho** [Quan666/ELF_RSS#273]
运行环境
    - Windows Server 2022 Datacenter 21H2
    - python  v3.9.10
    - go-cqhttp v1.0.0-rc1
    - ELF_RSS  v2.5.4

03-23 18:38:54 [INFO] ELF_RSS2 | test 检查更新
03-23 18:39:01 [ERROR] apscheduler | Job "check_update (trigger: interval[0:05:00], next run at: 2022-03-23 18:44:00 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Program Files\Python39\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Program Files\Python39\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "C:\Program Files\Python39\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Program Files\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Program Files\Python39\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Program Files\Python39\lib\site-packages\ELF_RSS2\RSS\util.py", line 13, in wrapper
    return await asyncio.wait_for(
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
  File "C:\Program Files\Python39\lib\site-packages\ELF_RSS2\RSS\my_trigger.py", line 16, in check_update
    await rss_parsing.start(rss)
  File "C:\Program Files\Python39\lib\site-packages\ELF_RSS2\RSS\rss_parsing.py", line 77, in start
    await pr.start(rss_name=rss.name, new_rss=new_rss)
  File "C:\Program Files\Python39\lib\site-packages\ELF_RSS2\RSS\routes\Parsing\__init__.py", line 218, in start
    tmp = await handler.func(
  File "C:\Program Files\Python39\lib\site-packages\ELF_RSS2\RSS\routes\Parsing\__init__.py", line 494, in handle_message
    if await send_msg(rss=rss, msg=item_msg, item=item):
  File "C:\Program Files\Python39\lib\site-packages\ELF_RSS2\RSS\routes\Parsing\send_message.py", line 14, in send_msg
    bot = nonebot.get_bot()
  File "C:\Program Files\Python39\lib\site-packages\nonebot\__init__.py", line 155, in get_bot
    raise ValueError("There are no bots to get.")
ValueError: There are no bots to get.

**Comment by mobyw** [comment]
检查一下 gocq 是不是掉线了

**Comment by YipSzeho** [comment]
看了几天，好像不是这个原因，重新安装后又不复现了
