### ISSUE TITLE
qBittorrent 能添加账号密码访问吗

### ISSUE THREAD

**Issue by xiaobaozi233** [Quan666/ELF_RSS#289]
请说明：

1. 需求：qBittorrent 能添加账号密码访问远程的服务器。
2. 理由：云服务器收到更新后可以直接远程下载回家里nas上的qb端，家里nas如果不设置账号密码公开有点风险。

**Comment by Quan666** [comment]
https://github.com/Quan666/ELF_RSS/tree/%23289
加上了，你试试这个分支

**Comment by xiaobaozi233** [comment]
`
04-29 11:42:38 [ERROR] src | 下载种子时出错
Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/bin/python3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/__main__.py", line 4,                                                                      in <module>
    main()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1128, in                                                                      __call__
    return self.main(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1053, in                                                                      main
    rv = self.invoke(ctx)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1637, in                                                                      invoke
    super().invoke(ctx)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1395, in                                                                      invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 754, in                                                                      invoke
    return __callback(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/decorators.py", line 26                                                                     , in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/__init__.py", line 35,                                                                      in main
    handle_no_subcommand()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/handlers/__init__.py",                                                                      line 58, in handle_no_subcommand
    result = subcommand()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", l                                                                     ine 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nonebot/__init__.py", line 30                                                                     0, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nonebot/drivers/fastapi.py",                                                                      line 232, in run
    uvicorn.run(
  File "/usr/local/bin/python3/lib/python3.9/site-packages/uvicorn/main.py", line 447, i                                                                     n run
    server.run()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/uvicorn/server.py", line 68,                                                                      in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/bin/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "./src/plugins/ELF_RSS2/RSS/my_trigger.py", line 17, in check_update
    await rss_parsing.start(rss)
  File "./src/plugins/ELF_RSS2/RSS/rss_parsing.py", line 76, in start
    await pr.start(rss_name=rss.name, new_rss=new_rss)
  File "./src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 204, in start
    tmp = await handler.func(
> File "./src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 488, in handle_torr                                                                     ent
    hash_list = await down_torrent(
  File "./src/plugins/ELF_RSS2/RSS/routes/Parsing/download_torrent.py", line 12, in down                                                                     _torrent
    for tmp in item["links"]:
KeyError: 'links'
04-29 11:42:38 [ERROR] src | 下载种子时出错
Traceback (most recent call last):
  File "/usr/local/bin/python3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/bin/python3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/__main__.py", line 4,                                                                      in <module>
    main()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1128, in                                                                      __call__
    return self.main(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1053, in                                                                      main
    rv = self.invoke(ctx)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1637, in                                                                      invoke
    super().invoke(ctx)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 1395, in                                                                      invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/core.py", line 754, in                                                                      invoke
    return __callback(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/click/decorators.py", line 26                                                                     , in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/__init__.py", line 35,                                                                      in main
    handle_no_subcommand()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/handlers/__init__.py",                                                                      line 58, in handle_no_subcommand
    result = subcommand()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", l                                                                     ine 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nonebot/__init__.py", line 30                                                                     0, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/bin/python3/lib/python3.9/site-packages/nonebot/drivers/fastapi.py",                                                                      line 232, in run
    uvicorn.run(
  File "/usr/local/bin/python3/lib/python3.9/site-packages/uvicorn/main.py", line 447, i                                                                     n run
    server.run()
  File "/usr/local/bin/python3/lib/python3.9/site-packages/uvicorn/server.py", line 68,                                                                      in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/bin/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "./src/plugins/ELF_RSS2/RSS/my_trigger.py", line 17, in check_update
    await rss_parsing.start(rss)
  File "./src/plugins/ELF_RSS2/RSS/rss_parsing.py", line 76, in start
    await pr.start(rss_name=rss.name, new_rss=new_rss)
  File "./src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 204, in start
    tmp = await handler.func(
> File "./src/plugins/ELF_RSS2/RSS/routes/Parsing/__init__.py", line 488, in handle_torr                                                                     ent
    hash_list = await down_torrent(
  File "./src/plugins/ELF_RSS2/RSS/routes/Parsing/download_torrent.py", line 12, in down                                                                     _torrent
    for tmp in item["links"]:
KeyError: 'links'
`

**Comment by xiaobaozi233** [comment]
手滑按错了。。报错上面这个

**Comment by Quan666** [comment]
rss地址呢

**Comment by xiaobaozi233** [comment]
https://mikanani.me/RSS/MyBangumi?token=OddQr2Z/WS+39KkDghLr7e33fGF3sxfwFZc8TSwxwVw=

**Comment by Quan666** [comment]
什么情况下出现的

**Comment by xiaobaozi233** [comment]
这个分支测试成功了，之前不行好像是蜜柑计划直连有问题，开了代理后可以下载了。
