### ISSUE TITLE
[nonebot_plugin_guild_patch] TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by YokiiroBW** [Quan666/ELF_RSS#326]
您好，我想请教一下，我刚下载的最新的版本，部署也成功了，但是启动后BOT并没有返回启动消息，指令也没有反应，后台看可以接收到消息，但是没有回应，想请教下是为什么，麻烦您了

```
PS C:\Users\Administrator\Desktop\BOT\ELF_RSS> nb run
07-16 11:15:27 [SUCCESS] nonebot | NoneBot is initializing...
07-16 11:15:27 [INFO] nonebot | Current Env: prod
07-16 11:15:29 [ERROR] nonebot | Failed to import "ELF_RSS2"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call
__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke

    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, i
n run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 20,
 in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 8, in <module>
    nonebot.load_plugins("src/plugins")
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 39, in
 load_plugins
    return manager.load_all_plugins()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 172
, in load_all_plugins
    return set(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 173
, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 148
, in load_plugin
    module = importlib.import_module(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 237
, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\src\plugins\ELF_RSS2\__init__.py", line 9, in <module>
    from . import command
  File ".\src\plugins\ELF_RSS2\command\__init__.py", line 1, in <module>
    from . import (
  File ".\src\plugins\ELF_RSS2\command\add_dy.py", line 10, in <module>
    from nonebot_plugin_guild_patch import GuildMessageEvent
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_guild_patch\__init__.
py", line 6, in <module>
    from .models import (
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_guild_patch\models.py
", line 30, in <module>
    class GuildMessageEvent(MessageEvent):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_guild_patch\models.py
", line 88, in GuildMessageEvent
    def _check_at_me(message: Message, self_tiny_id: int) -> tuple[Message, bool]:
TypeError: 'type' object is not subscriptable
07-16 11:15:29 [SUCCESS] nonebot | Running NoneBot...
07-16 11:15:30 [INFO] uvicorn | Started server process [9212]
07-16 11:15:30 [INFO] uvicorn | Waiting for application startup.
07-16 11:15:30 [INFO] uvicorn | Application startup complete.
07-16 11:15:30 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:9090 (Press CTRL+C to quit)
07-16 11:15:30 [INFO] uvicorn | ('127.0.0.1', 58263) - "WebSocket /onebot/v11/ws/" [accepted]
07-16 11:15:30 [INFO] nonebot | OneBot V11 | Bot 1449801200 connected
07-16 11:15:30 [INFO] websockets | connection open


```

**Comment by NekoAria** [comment]
看样子是 Python 版本低于 3.9 遇到的问题，具体看 [nonebot-plugin-guild-patch#5](https://github.com/mnixry/nonebot-plugin-guild-patch/issues/5) 。

**Comment by NekoAria** [comment]
如果不想等那边修复，直接换个不低于 3.9 的 Python 版本吧。

**Comment by YokiiroBW** [comment]
好的，我试一下

**Comment by YokiiroBW** [comment]
之前应用的是部署教程里的3.8.3的python，然后换到了3.9.13以后BOT有响应了，再次感谢
