### ISSUE TITLE
启动错误 'type' object is not subscriptable 

### ISSUE THREAD

**Issue by WM9116** [Quan666/ELF_RSS#327]
如果不是汇报 bug 或请求新功能，请尽量不要提 issue，视情况我们可能会直接关闭
你好大佬，已经通过 pip install -r requirements.txt 安装依赖，typing_extension 版本 4.3.0

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bot/./bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bot/./src/plugins/ELF_RSS2/__init__.py", line 9, in <module>
    from . import command
  File "/home/bot/./src/plugins/ELF_RSS2/command/__init__.py", line 1, in <module>
    from . import (
  File "/home/bot/./src/plugins/ELF_RSS2/command/add_dy.py", line 10, in <module>
    from nonebot_plugin_guild_patch import GuildMessageEvent
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot_plugin_guild_patch/__init__.py", line 6, in <module>
    from .models import (
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot_plugin_guild_patch/models.py", line 30, in <module>
    class GuildMessageEvent(MessageEvent):
  File "/root/.cache/pypoetry/virtualenvs/bot-3nGdubw0-py3.8/lib/python3.8/site-packages/nonebot_plugin_guild_patch/models.py", line 88, in GuildMessageEvent
    def _check_at_me(message: Message, self_tiny_id: int) -> tuple[Message, bool]:
TypeError: 'type' object is not subscriptable

**Comment by NekoAria** [comment]
和 #326 一样的情况

**Comment by WM9116** [comment]
好的谢谢 ，抱歉啊，提问之前搜索issues相关的问题没搜到，我的我的
