### ISSUE TITLE
自动部署相关问题

### ISSUE THREAD

**Issue by CiaranZhou** [Quan666/ELF_RSS#35]
环境ubuntu16.04

1.`sh install.sh`处
直接使用sh会报运算符错误。其实应该使用更强大的bash，也就是`./install.sh`，前提是需要修改权限`chmod a+x ./install.sh`

2.`install.sh`文件中
`cp ./ELF_RSS /app`会导致目录结构为`/app/ELF_RSS/`且不会复制隐藏文件，观察了一下后续的提示此处应该为`cp -ar ./ELF_RSS/. /app`

3.`install.sh`运行中
参数依次为1 2
期间有报错如下
```ERROR: nonebot-plugin-apscheduler 0.1.2 has requirement apscheduler<4.0.0,>=3.7.0, but you'll have apscheduler 3.6.3 which is incompatible.```

4.修改完配置文件且利用`install.sh`重启后
~~其实`install.sh`运行完就有该错误~~
修改新install.sh文件的权限后，利用`install.sh`查看日志如下
```
01-31 11:20:39 [INFO] nonebot | NoneBot is initializing...
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 167, in pydantic.env_settings.read_env_file
ModuleNotFoundError: No module named 'dotenv'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/__init__.py", line 46, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers.py", line 44, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 16, in <module>
    nonebot.init()
  File "/usr/local/lib/python3.8/site-packages/nonebot/__init__.py", line 174, in init
    env = Env()
  File "pydantic/env_settings.py", line 35, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 48, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 100, in pydantic.env_settings.BaseSettings._build_environ
  File "pydantic/env_settings.py", line 169, in pydantic.env_settings.read_env_file
ImportError: python-dotenv is not installed, run `pip install pydantic[dotenv]`
```

手动运行`nb run`没有问题

**Comment by Quan666** [comment]
你可以修改测试后提交 pr，我 shell 脚本写的少

**Comment by Quan666** [comment]
273023becfdb82300c56d6a00d29f50d503b282b
