### ISSUE TITLE
修改订阅信息时发生错误 AttributeError: 'ELFConfig' object has no attribute 'debug'

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [Quan666/ELF_RSS#419]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

ELF_RSS=2.6.17
go-cqhttp=2.0.0rc4
nonebot2
python=3.9.13

### 如何复现

使用change命令修改订阅信息以及检查订阅更新时报错无法修改或更新

### 实际行为

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "F:\nonebot\QQbot\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "F:\nonebot\QQbot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "F:\nonebot\QQbot\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "F:\nonebot\QQbot\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files (x86)\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files (x86)\python38\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "c:\program files (x86)\python38\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "c:\program files (x86)\python38\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\program files (x86)\python38\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\program files (x86)\python38\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "F:\nonebot\QQbot\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "F:\nonebot\QQbot\.venv\lib\site-packages\ELF_RSS2\my_trigger.py", line 23, in check_update
    await asyncio.wait_for(rss_parsing.start(rss), timeout=wait_for)
  File "c:\program files (x86)\python38\lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
  File "F:\nonebot\QQbot\.venv\lib\site-packages\ELF_RSS2\rss_parsing.py", line 82, in start
    new_rss, cached = await fetch_rss(rss)
  File "F:\nonebot\QQbot\.venv\lib\site-packages\ELF_RSS2\rss_parsing.py", line 163, in fetch_rss
    if not config.rsshub_backup and not config.debug:
AttributeError: 'ELFConfig' object has no attribute 'debug'

日志中py所在文件夹名字是38 实际上是3.9 因为之前安装3.8后有的插件无法运行 所以使用3.9再安装了一次

**Comment by NekoAria** [comment]
Duplicate of #413

**Comment by NekoAria** [comment]
请协助测试 fix 分支，这个分支包括对这个 issue 的修复。

**Comment by KiDisplayBlueScreen** [comment]
> 请协助测试 fix 分支，这个分支包括对这个 issue 的修复。

![W{7I88629P1)YQBWB J`CB3](https://user-images.githubusercontent.com/33929772/231461863-de1af423-beb1-4b04-be2d-a4237775ad4e.png)
是这里吗?

**Comment by NekoAria** [comment]
你如果直接往 config.py 加入这行也行。

但还是建议直接使用 fix 分支，因为有些其他问题被修正。

**Comment by KiDisplayBlueScreen** [comment]
> 你如果直接往 config.py 加入这行也行。
> 
> 但还是建议直接使用 fix 分支，因为有些其他问题被修正。

还是报错 我直接删除and not config.debug这一句 貌似可以了 会有什么问题吗

**Comment by NekoAria** [comment]
> > 你如果直接往 config.py 加入这行也行。
> > 
> > 但还是建议直接使用 fix 分支，因为有些其他问题被修正。
> 
> 还是报错 我直接删除and not config.debug这一句 貌似可以了 会有什么问题吗

哦，说错了，你放的位置不对，应该是在 class Config 外，你放到里面了。
具体有什么其他的问题请看 fix 分支的提交记录。
