### ISSUE TITLE
图片下载失败以及寻找不到图片路径问题

### ISSUE THREAD

**Issue by kksmi** [Quan666/ELF_RSS#44]
你好在更新之后会出现这样的报错
_03-08 18:07:06 [ERROR] apscheduler | Job "check_update (trigger: interval[0:03:00], next run at: 2021-03-08 18:10:06 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/usr/local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "src/plugins/ELF_RSS2/RSSHUB/rsstrigger.py", line 14, in check_update
    await RSS_Parsing.start(rss)
  File "src/plugins/ELF_RSS2/RSSHUB/RSS_Parsing.py", line 106, in start
    item_msg += await handle_summary(summary=item['summary'], rss=rss)
  File "src/plugins/ELF_RSS2/RSSHUB/RSS_Parsing.py", line 227, in handle_summary
    res_msg += await handle_img(html=summary_html, img_proxy=rss.img_proxy)
  File "src/plugins/ELF_RSS2/RSSHUB/RSS_Parsing.py", line 380, in handle_img
    img_str += '[CQ:image,file=base64://' + await get_pic_base64(str(img_path)) + ']'
  File "src/plugins/ELF_RSS2/RSSHUB/RSS_Parsing.py", line 357, in get_pic_base64
    async with aiofiles.open(path, mode='rb') as f:
  File "/usr/local/lib/python3.8/site-packages/aiofiles/base.py", line 75, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'home/pi/usbks32g/kk/ELF_RSS-2.0/data/imgs/2bdb60b5-3d12-483e-89bc-e652c348bbc5.jpg'_

但却能在imgs路径下看到相关图片，而且重复的很多，如何解决，非常感谢

**Comment by Quan666** [comment]
Linux？把isLinux设为true没？
