### ISSUE TITLE
BOT已连接无响应

### ISSUE THREAD

**Issue by zzz6839** [Quan666/ELF_RSS#482]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

ELF_RSS docker compose 版本 ubuntu 
commit是这个：c72c7ae63f76079fd2f90a5f1752b3472b0528b5

### 如何复现

```
git clone https://github.com/Quan666/ELF_RSS


docker compose up -d,
```
 build完就不行了，bot不理人

### 期望行为

bot有回应

### 实际行为

```
02/05/2024
07:36:05 PM
02-05 19:36:05 [SUCCESS] nonebot | NoneBot is initializing...
02/05/2024
07:36:05 PM
02-05 19:36:05 [INFO] nonebot | Current Env: prod
02/05/2024
07:36:06 PM
02-05 19:36:06 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
02/05/2024
07:36:06 PM
02-05 19:36:06 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
02/05/2024
07:36:06 PM
02-05 19:36:06 [ERROR] nonebot | Failed to import "ELF_RSS2"
02/05/2024
07:36:06 PM
Traceback (most recent call last):
02/05/2024
07:36:06 PM
  File "bot.py", line 8, in <module>
02/05/2024
07:36:06 PM
    nonebot.load_plugins("src/plugins")
02/05/2024
07:36:06 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 50, in load_plugins
02/05/2024
07:36:06 PM
    return manager.load_all_plugins()
02/05/2024
07:36:06 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
02/05/2024
07:36:06 PM
    return set(
02/05/2024
07:36:06 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
02/05/2024
07:36:06 PM
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
02/05/2024
07:36:06 PM
> File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
02/05/2024
07:36:06 PM
    module = importlib.import_module(
02/05/2024
07:36:06 PM
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
02/05/2024
07:36:06 PM
    return _bootstrap._gcd_import(name[level:], package, level)
02/05/2024
07:36:06 PM
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
02/05/2024
07:36:06 PM
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
02/05/2024
07:36:06 PM
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
02/05/2024
07:36:06 PM
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
02/05/2024
07:36:06 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
02/05/2024
07:36:06 PM
    super().exec_module(module)
02/05/2024
07:36:06 PM
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
02/05/2024
07:36:06 PM
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/__init__.py", line 11, in <module>
02/05/2024
07:36:06 PM
    from . import command
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/command/__init__.py", line 1, in <module>
02/05/2024
07:36:06 PM
    from . import (
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/command/add_cookies.py", line 9, in <module>
02/05/2024
07:36:06 PM
    from .. import my_trigger as tr
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/my_trigger.py", line 11, in <module>
02/05/2024
07:36:06 PM
    from . import rss_parsing
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/rss_parsing.py", line 12, in <module>
02/05/2024
07:36:06 PM
    from .parsing import get_proxy
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/parsing/__init__.py", line 21, in <module>
02/05/2024
07:36:06 PM
    from .download_torrent import down_torrent, pikpak_offline
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/parsing/download_torrent.py", line 10, in <module>
02/05/2024
07:36:06 PM
    from ..pikpak_offline import pikpak_offline_download
02/05/2024
07:36:06 PM
  File "/app/src/plugins/ELF_RSS2/pikpak_offline.py", line 5, in <module>
02/05/2024
07:36:06 PM
    from pikpakapi.PikpakException import PikpakAccessTokenExpireException, PikpakException
02/05/2024
07:36:06 PM
ImportError: cannot import name 'PikpakAccessTokenExpireException' from 'pikpakapi.PikpakException' (/usr/local/lib/python3.8/site-packages/pikpakapi/PikpakException.py)
02/05/2024
07:36:06 PM
02-05 19:36:06 [SUCCESS] nonebot | Running NoneBot...
02/05/2024
07:36:06 PM
02-05 19:36:06 [INFO] uvicorn | Started server process [17]
02/05/2024
07:36:06 PM
02-05 19:36:06 [INFO] uvicorn | Waiting for application startup.
02/05/2024
07:36:06 PM
02-05 19:36:06 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02/05/2024
07:36:06 PM
02-05 19:36:06 [INFO] uvicorn | Application startup complete.
02/05/2024
07:36:06 PM
02-05 19:36:06 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:6080 (Press CTRL+C to quit)
02/05/2024
07:36:08 PM
02-05 19:36:08 [INFO] uvicorn | ('172.27.96.1', 50993) - "WebSocket /onebot/v11/ws/" [accepted]
02/05/2024
07:36:08 PM
02-05 19:36:08 [INFO] nonebot | OneBot V11 | Bot 3 8392 connected
02/05/2024
07:36:08 PM
02-05 19:36:08 [INFO] websockets | connection open
02/05/2024
07:39:08 PM
02-05 19:39:08 [SUCCESS] nonebot | OneBot V11 332 8392 | [message.private.friend]: Message 1162347483 from 343 730 'sho_all'
02/05/2024
07:39:13 PM
02-05 19:39:13 [SUCCESS] nonebot | OneBot V11 33 8392 | [message.private.friend]: Message 290823866 from 343 730 'show_all'
02/05/2024
07:41:50 PM
02-05 19:41:50 [SUCCESS] nonebot | OneBot V11 332 92 | [message.private.friend]: Message 1755239063 from 34 730 'showall'
02/05/2024
07:42:03 PM
02-05 19:42:03 [SUCCESS] nonebot | OneBot V11 332 92 | [message.private.friend]: Message 1751769373 from 3438 30 'show'
02/05/2024
07:42:41 PM
02-05 19:42:41 [SUCCESS] nonebot | OneBot V11 3325348392 | [message.group.normal]: Message 1118574202 from 3 0@[群: 586] '[at:qq= ] showall'

**Comment by zzz6839** [comment]
.env.prod有指定超级用户

**Comment by Quan666** [comment]
更新下这个库呢
pikpakapi

**Comment by zzz6839** [comment]
> 更新下这个库呢 pikpakapi

手动修改pikpakapi~=0.1.6，build完依旧老样子不理我
```
02/07/2024
02:50:43 PM
02-07 14:50:43 [SUCCESS] nonebot | NoneBot is initializing...
02/07/2024
02:50:43 PM
02-07 14:50:43 [INFO] nonebot | Current Env: prod
02/07/2024
02:50:43 PM
02-07 14:50:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
02/07/2024
02:50:43 PM
02-07 14:50:43 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
02/07/2024
02:50:44 PM
02-07 14:50:44 [ERROR] nonebot | Failed to import "ELF_RSS2"
02/07/2024
02:50:44 PM
Traceback (most recent call last):
02/07/2024
02:50:44 PM
  File "bot.py", line 8, in <module>
02/07/2024
02:50:44 PM
    nonebot.load_plugins("src/plugins")
02/07/2024
02:50:44 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 50, in load_plugins
02/07/2024
02:50:44 PM
    return manager.load_all_plugins()
02/07/2024
02:50:44 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
02/07/2024
02:50:44 PM
    return set(
02/07/2024
02:50:44 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
02/07/2024
02:50:44 PM
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
02/07/2024
02:50:44 PM
> File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
02/07/2024
02:50:44 PM
    module = importlib.import_module(
02/07/2024
02:50:44 PM
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
02/07/2024
02:50:44 PM
    return _bootstrap._gcd_import(name[level:], package, level)
02/07/2024
02:50:44 PM
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
02/07/2024
02:50:44 PM
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
02/07/2024
02:50:44 PM
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
02/07/2024
02:50:44 PM
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
02/07/2024
02:50:44 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
02/07/2024
02:50:44 PM
    super().exec_module(module)
02/07/2024
02:50:44 PM
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
02/07/2024
02:50:44 PM
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/__init__.py", line 11, in <module>
02/07/2024
02:50:44 PM
    from . import command
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/command/__init__.py", line 1, in <module>
02/07/2024
02:50:44 PM
    from . import (
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/command/add_cookies.py", line 9, in <module>
02/07/2024
02:50:44 PM
    from .. import my_trigger as tr
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/my_trigger.py", line 11, in <module>
02/07/2024
02:50:44 PM
    from . import rss_parsing
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/rss_parsing.py", line 12, in <module>
02/07/2024
02:50:44 PM
    from .parsing import get_proxy
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/parsing/__init__.py", line 21, in <module>
02/07/2024
02:50:44 PM
    from .download_torrent import down_torrent, pikpak_offline
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/parsing/download_torrent.py", line 10, in <module>
02/07/2024
02:50:44 PM
    from ..pikpak_offline import pikpak_offline_download
02/07/2024
02:50:44 PM
  File "/app/src/plugins/ELF_RSS2/pikpak_offline.py", line 5, in <module>
02/07/2024
02:50:44 PM
    from pikpakapi.PikpakException import PikpakAccessTokenExpireException, PikpakException
02/07/2024
02:50:44 PM
ImportError: cannot import name 'PikpakAccessTokenExpireException' from 'pikpakapi.PikpakException' (/usr/local/lib/python3.8/site-packages/pikpakapi/PikpakException.py)
02/07/2024
02:50:44 PM
02-07 14:50:44 [SUCCESS] nonebot | Running NoneBot...
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] uvicorn | Started server process [17]
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] uvicorn | Waiting for application startup.
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] uvicorn | Application startup complete.
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:6080 (Press CTRL+C to quit)
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] uvicorn | ('172.27.96.1', 54755) - "WebSocket /onebot/v11/ws/" [accepted]
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] nonebot | OneBot V11 | Bot 3 392 connected
02/07/2024
02:50:44 PM
02-07 14:50:44 [INFO] websockets | connection open
02/07/2024
02:54:31 PM
02-07 14:54:31 [SUCCESS] nonebot | OneBot V11 33292 | [message.private.friend]: Message 202626 from 34 730 'showall'
```

**Comment by Quan666** [comment]
改成0.1.3版本吧

**Comment by zzz6839** [comment]
。。。这个一开始用的就是0.1.3版本，话说为什么不提供一个build好的镜像放在hub那里要用户本地build，依赖会出问题，不是很理解。。。

**Comment by Quan666** [comment]
试试 #483 这个更改

**Comment by zzz6839** [comment]
> 试试 #483 这个更改

一样不理人，是因为我用的目前不是cqhttp而是openshamrock有关吗？https://github.com/whitechi73/OpenShamrock
```
02/08/2024
11:31:45 PM
02-08 23:31:45 [SUCCESS] nonebot | NoneBot is initializing...
02/08/2024
11:31:45 PM
02-08 23:31:45 [INFO] nonebot | Current Env: prod
02/08/2024
11:31:45 PM
02-08 23:31:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
02/08/2024
11:31:45 PM
02-08 23:31:45 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
02/08/2024
11:31:46 PM
02-08 23:31:46 [ERROR] nonebot | Failed to import "ELF_RSS2"
02/08/2024
11:31:46 PM
Traceback (most recent call last):
02/08/2024
11:31:46 PM
  File "bot.py", line 8, in <module>
02/08/2024
11:31:46 PM
    nonebot.load_plugins("src/plugins")
02/08/2024
11:31:46 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 50, in load_plugins
02/08/2024
11:31:46 PM
    return manager.load_all_plugins()
02/08/2024
11:31:46 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
02/08/2024
11:31:46 PM
    return set(
02/08/2024
11:31:46 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
02/08/2024
11:31:46 PM
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
02/08/2024
11:31:46 PM
> File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
02/08/2024
11:31:46 PM
    module = importlib.import_module(
02/08/2024
11:31:46 PM
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
02/08/2024
11:31:46 PM
    return _bootstrap._gcd_import(name[level:], package, level)
02/08/2024
11:31:46 PM
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
02/08/2024
11:31:46 PM
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
02/08/2024
11:31:46 PM
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
02/08/2024
11:31:46 PM
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
02/08/2024
11:31:46 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
02/08/2024
11:31:46 PM
    super().exec_module(module)
02/08/2024
11:31:46 PM
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
02/08/2024
11:31:46 PM
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/__init__.py", line 11, in <module>
02/08/2024
11:31:46 PM
    from . import command
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/command/__init__.py", line 1, in <module>
02/08/2024
11:31:46 PM
    from . import (
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/command/add_cookies.py", line 9, in <module>
02/08/2024
11:31:46 PM
    from .. import my_trigger as tr
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/my_trigger.py", line 11, in <module>
02/08/2024
11:31:46 PM
    from . import rss_parsing
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/rss_parsing.py", line 12, in <module>
02/08/2024
11:31:46 PM
    from .parsing import get_proxy
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/parsing/__init__.py", line 21, in <module>
02/08/2024
11:31:46 PM
    from .download_torrent import down_torrent, pikpak_offline
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/parsing/download_torrent.py", line 10, in <module>
02/08/2024
11:31:46 PM
    from ..pikpak_offline import pikpak_offline_download
02/08/2024
11:31:46 PM
  File "/app/src/plugins/ELF_RSS2/pikpak_offline.py", line 9, in <module>
02/08/2024
11:31:46 PM
    pikpak_client = PikPakApi(
02/08/2024
11:31:46 PM
  File "/usr/local/lib/python3.8/site-packages/pikpakapi/__init__.py", line 69, in __init__
02/08/2024
11:31:46 PM
    raise PikpakException("username and password or encoded_token is required")
02/08/2024
11:31:46 PM
pikpakapi.PikpakException.PikpakException: username and password or encoded_token is required
02/08/2024
11:31:46 PM
02-08 23:31:46 [SUCCESS] nonebot | Running NoneBot...
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] uvicorn | Started server process [16]
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] uvicorn | Waiting for application startup.
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] uvicorn | Application startup complete.
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:6080 (Press CTRL+C to quit)
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] uvicorn | ('172.17.0.1', 58542) - "WebSocket /onebot/v11/ws/" [accepted]
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] nonebot | OneBot V11 | Bot 33292 connected
02/08/2024
11:31:46 PM
02-08 23:31:46 [INFO] websockets | connection open
02/08/2024
11:32:58 PM
02-08 23:32:58 [SUCCESS] nonebot | OneBot V11 332392 | [message.private.friend]: Message 1224 from 343730 'showall'
```

**Comment by Quan666** [comment]
不是，是bug，你降级到0.1.2版本试试

**Comment by zzz6839** [comment]
> 不是，是bug，你降级到0.1.2版本试试

不行，降级了也没用。我pikpak相关配置在.env.prod里注释掉也还是一样的问题，还用了你pr里的pikpakoffline.py文件

```
02/09/2024
01:34:30 PM
02-09 13:34:30 [SUCCESS] nonebot | NoneBot is initializing...
02/09/2024
01:34:30 PM
02-09 13:34:30 [INFO] nonebot | Current Env: prod
02/09/2024
01:34:31 PM
02-09 13:34:31 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
02/09/2024
01:34:31 PM
02-09 13:34:31 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_guild_patch"
02/09/2024
01:34:31 PM
02-09 13:34:31 [ERROR] nonebot | Failed to import "ELF_RSS2"
02/09/2024
01:34:31 PM
Traceback (most recent call last):
02/09/2024
01:34:31 PM
  File "bot.py", line 8, in <module>
02/09/2024
01:34:31 PM
    nonebot.load_plugins("src/plugins")
02/09/2024
01:34:31 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/load.py", line 50, in load_plugins
02/09/2024
01:34:31 PM
    return manager.load_all_plugins()
02/09/2024
01:34:31 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
02/09/2024
01:34:31 PM
    return set(
02/09/2024
01:34:31 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
02/09/2024
01:34:31 PM
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
02/09/2024
01:34:31 PM
> File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 146, in load_plugin
02/09/2024
01:34:31 PM
    module = importlib.import_module(
02/09/2024
01:34:31 PM
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
02/09/2024
01:34:31 PM
    return _bootstrap._gcd_import(name[level:], package, level)
02/09/2024
01:34:31 PM
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
02/09/2024
01:34:31 PM
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
02/09/2024
01:34:31 PM
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
02/09/2024
01:34:31 PM
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
02/09/2024
01:34:31 PM
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
02/09/2024
01:34:31 PM
    super().exec_module(module)
02/09/2024
01:34:31 PM
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
02/09/2024
01:34:31 PM
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/__init__.py", line 11, in <module>
02/09/2024
01:34:31 PM
    from . import command
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/command/__init__.py", line 1, in <module>
02/09/2024
01:34:31 PM
    from . import (
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/command/add_cookies.py", line 9, in <module>
02/09/2024
01:34:31 PM
    from .. import my_trigger as tr
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/my_trigger.py", line 11, in <module>
02/09/2024
01:34:31 PM
    from . import rss_parsing
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/rss_parsing.py", line 12, in <module>
02/09/2024
01:34:31 PM
    from .parsing import get_proxy
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/parsing/__init__.py", line 21, in <module>
02/09/2024
01:34:31 PM
    from .download_torrent import down_torrent, pikpak_offline
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/parsing/download_torrent.py", line 10, in <module>
02/09/2024
01:34:31 PM
    from ..pikpak_offline import pikpak_offline_download
02/09/2024
01:34:31 PM
  File "/app/src/plugins/ELF_RSS2/pikpak_offline.py", line 9, in <module>
02/09/2024
01:34:31 PM
    pikpak_client = PikPakApi(
02/09/2024
01:34:31 PM
  File "/usr/local/lib/python3.8/site-packages/pikpakapi/__init__.py", line 69, in __init__
02/09/2024
01:34:31 PM
    raise PikpakException("username and password or encoded_token is required")
02/09/2024
01:34:31 PM
pikpakapi.PikpakException.PikpakException: username and password or encoded_token is required
02/09/2024
01:34:31 PM
02-09 13:34:31 [SUCCESS] nonebot | Running NoneBot...
02/09/2024
01:34:31 PM
02-09 13:34:31 [INFO] uvicorn | Started server process [18]
02/09/2024
01:34:31 PM
02-09 13:34:31 [INFO] uvicorn | Waiting for application startup.
02/09/2024
01:34:31 PM
02-09 13:34:31 [INFO] nonebot_plugin_apscheduler | Scheduler Started
02/09/2024
01:34:31 PM
02-09 13:34:31 [INFO] uvicorn | Application startup complete.
02/09/2024
01:34:31 PM
02-09 13:34:31 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:6080 (Press CTRL+C to quit)
02/09/2024
01:34:32 PM
02-09 13:34:32 [INFO] uvicorn | ('172.17.0.1', 50180) - "WebSocket /onebot/v11/ws/" [accepted]
02/09/2024
01:34:32 PM
02-09 13:34:32 [INFO] nonebot | OneBot V11 | Bot 3322 connected
02/09/2024
01:34:32 PM
02-09 13:34:32 [INFO] websockets | connection open
02/09/2024
01:35:06 PM
02-09 13:35:06 [SUCCESS] nonebot | OneBot V11 3392 | [message.private.friend]: Message 5230 from 34330 'showall'
```

**Comment by Quan666** [comment]
配置随便填个
