### ISSUE TITLE
nonebot-plugin-guild-patch已经撤包了，希望能移除依赖

### ISSUE THREAD

**Issue by liuzj288** [Quan666/ELF_RSS#499]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

nonebot-plugin-guild-patch已经撤包了，希望能移除依赖

### 如何复现

nonebot-plugin-guild-patch已经撤包了，希望能移除依赖

### 实际行为

nonebot-plugin-guild-patch已经撤包了，希望能移除依赖

**Comment by liuzj288** [comment]
这样报错 nonebot-plugin-guild-patch

https://registry.nonebot.dev/plugin/ELF-RSS:ELF_RSS2

**Comment by Quan666** [comment]
> 这样报错 nonebot-plugin-guild-patch
> 
> https://registry.nonebot.dev/plugin/ELF-RSS:ELF_RSS2

你会改吗？要不你帮忙改一下

**Comment by liuzj288** [comment]
> > 这样报错 nonebot-plugin-guild-patch
> > https://registry.nonebot.dev/plugin/ELF-RSS:ELF_RSS2
> 
> 你会改吗？要不你帮忙改一下

今天重新部署卡在这里了，回退版本好像也不行，研究nonebot不是很深入，定位不到原因

    
05-10 14:29:14 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
05-10 14:29:14 [ERROR] nonebot | Failed to import "nonebot_plugin_guild_patch"
Traceback (most recent call last):
  File "C:\Users\liuzj\Documents\ELF_RSS\bot.py", line 8, in <module>
    nonebot.load_plugins("src/plugins")
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\load.py", line 51, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "C:\Users\liuzj\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\liuzj\Documents\ELF_RSS\src\plugins\ELF_RSS2\__init__.py", line 9, in <module>
    require("nonebot_plugin_guild_patch")
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\load.py", line 185, in require
    plugin = load_plugin(name)
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\liuzj\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot_plugin_guild_patch\__init__.py", line 6, in <module>
    from .models import (
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 30, in <module>
    class GuildMessageEvent(MessageEvent):
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot_plugin_guild_patch\models.py", line 50, in GuildMessageEvent
    @root_validator(pre=False)
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\pydantic\deprecated\class_validators.py", line 249, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.7/u/root-validator-pre-skip
05-10 14:29:14 [ERROR] nonebot | Failed to import "ELF_RSS2"
Traceback (most recent call last):
  File "C:\Users\liuzj\Documents\ELF_RSS\bot.py", line 8, in <module>
    nonebot.load_plugins("src/plugins")
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\load.py", line 51, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "C:\Users\liuzj\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\liuzj\Documents\ELF_RSS\src\plugins\ELF_RSS2\__init__.py", line 9, in <module>
    require("nonebot_plugin_guild_patch")
  File "C:\Users\liuzj\Documents\ELF_RSS\venv\lib\site-packages\nonebot\plugin\load.py", line 188, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_guild_patch"!

**Comment by Quan666** [comment]
用docker 装上一个版本试试

**Comment by liuzj288** [comment]
> > 这样报错 nonebot-plugin-guild-patch
> > https://registry.nonebot.dev/plugin/ELF-RSS:ELF_RSS2
> 
> 你会改吗？要不你帮忙改一下

强行把涉及到guild的代码删除了，现在出现个问题，拼订阅链接的时候出现多了个斜杠

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/ee9b6b8f-b9a7-4f15-b5dc-902517c4be49)

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/4e572d1d-5d27-4561-86d1-e7b5cc63a23d)

这个代码是在哪里拼的

**Comment by Quan666** [comment]
https://github.com/Quan666/ELF_RSS/tree/remove-nonebot_plugin_guild_patch

试试这个分支

**Comment by liuzj288** [comment]
> https://github.com/Quan666/ELF_RSS/tree/remove-nonebot_plugin_guild_patch
> 
> 试试这个分支

试了下，自己搭的RSS源还是中间两条杠导致失败，真是奇怪

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/6fe3a51d-8d16-4c1b-a3c0-8e1cf4784971)

env文件里变量最后是没加/的

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/d37a1d86-7196-4085-bb8f-d94e8cc1f2b6)

**Comment by Quan666** [comment]
删掉订阅重新添加

**Comment by liuzj288** [comment]
> 删掉订阅重新添加

强行改死rss_class.py目前可行

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/1e857c10-0c5a-4e0e-993c-c5ac5e75ef8c)

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/5ccc3367-ad4e-4952-a7b3-4748ce0717b8)

否则只是删掉订阅重新添加问题依旧

![image](https://github.com/Quan666/ELF_RSS/assets/13833404/c158606b-ca78-4175-b7a1-d3c88e473fc6)

**Comment by Quan666** [comment]
你添加订阅的命令什么样的
