### ISSUE TITLE
BOT连接后无任何回应

### ISSUE THREAD

**Issue by kyohei-sama** [Quan666/ELF_RSS#536]
### ELF_RSS 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

使用Lagrange.OneBot，python3.10.12，ELF_RSS最新版本，Ubuntu 22.04 LTS

09-16 09:18:08 [SUCCESS] nonebot | NoneBot is initializing...
09-16 09:18:08 [INFO] nonebot | Current Env: prod
09-16 09:18:09 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
09-16 09:18:09 [ERROR] nonebot | Failed to import "ELF_RSS2"
Traceback (most recent call last):
  File "/app/bot.py", line 8, in <module>
    nonebot.load_plugins("src/plugins")
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/load.py", line 51, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/plugins/ELF_RSS2/__init__.py", line 10, in <module>
    from . import command
  File "/app/src/plugins/ELF_RSS2/command/__init__.py", line 1, in <module>
    from . import (
  File "/app/src/plugins/ELF_RSS2/command/add_cookies.py", line 9, in <module>
    from .. import my_trigger as tr
  File "/app/src/plugins/ELF_RSS2/my_trigger.py", line 11, in <module>
    from . import rss_parsing
  File "/app/src/plugins/ELF_RSS2/rss_parsing.py", line 12, in <module>
    from .parsing import get_proxy
  File "/app/src/plugins/ELF_RSS2/parsing/__init__.py", line 13, in <module>
    from ..rss_class import Rss
  File "/app/src/plugins/ELF_RSS2/rss_class.py", line 53
    return f"{rsshub.rstrip("/")}/{self.url.lstrip("/")}"
                             ^
SyntaxError: f-string: unmatched '('
09-16 09:18:09 [SUCCESS] nonebot | Running NoneBot...
09-16 09:18:09 [INFO] uvicorn | Started server process [16]
09-16 09:18:09 [INFO] uvicorn | Waiting for application startup.
09-16 09:18:09 [INFO] nonebot_plugin_apscheduler | Scheduler Started
09-16 09:18:09 [INFO] uvicorn | Application startup complete.
09-16 09:18:09 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:18496 (Press CTRL+C to quit)
09-16 09:18:13 [INFO] uvicorn | ('172.17.0.1', 53924) - "WebSocket /onebot/v11/ws" [accepted]
09-16 09:18:13 [INFO] nonebot | OneBot V11 | Bot 270XXXX480 connected
09-16 09:18:13 [INFO] websockets | connection open
09-16 09:19:28 [SUCCESS] nonebot | OneBot V11 270XXXX480 | [message.group.normal]: Message -114xxx883 from 125xxxx440@[群:101XXXX61] '[at:qq=270xxxx480,name=@开XXXX站] #add test twitter/user/huagequan'

### 如何复现

能收到消息，但是任何消息不理睬，也没有发送开机消息，尝试更换命令起始字符"","/","#"均无效果。
分别尝试使用pip和docker均为同样效果，请求帮助，感谢。

### 实际行为

配置文件：
配置 NoneBot 监听的 IP/主机名
HOST=0.0.0.0
配置 NoneBot 监听的端口
PORT=18496
开启 debug 模式 **请勿在生产环境开启**
DEBUG=true
配置 NoneBot 超级用户：管理员qq，支持多管理员，逗号分隔 注意，启动消息只发送给第一个管理员
SUPERUSERS=["32xxxx30"]
配置机器人的昵称
NICKNAME=["bot"]
配置命令起始字符
COMMAND_START=["#"]
配置命令分割字符
COMMAND_SEP=["."]`

**Comment by Quan666** [comment]
更新到最新版本再试试
