### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'STATUS_CODE'

### ISSUE THREAD

**Issue by yoiyami96** [Quan666/ELF_RSS#78]
以插件形式添加elf_rss2.2.2版本会报错，日志如下，新增依赖已安装，回退2.2.1则一切正常

05-09 07:56:43 [INFO] nonebot | 涩图bot 检查更新
05-09 07:56:43 [ERROR] nonebot | 图片[https://pbs.twimg.com/media/E05XWiBVgAAXPg
x?format=jpg&name=orig]下载失败,将重试
 'Response' object has no attribute 'STATUS_CODE'
05-09 07:56:43 [ERROR] apscheduler | Job "check_update (trigger: interval[0:02:0
0], next run at: 2021-05-09 07:58:48 CST)" raised an exception
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.
py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb
.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\nonebot\drivers\fastapi.py", line 160, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\uvicorn\main.py", line 386, in run
    server.run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\base_events.py", line 596, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\base_events.py", line 1890, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-p
ackages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "src/plugins\ELF_RSS2\RSS\util.py", line 13, in wrapper
    return await asyncio.wait_for(method(self, *args, **kwargs), timeout=time)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\asynci
o\tasks.py", line 481, in wait_for
    return fut.result()
  File "src/plugins\ELF_RSS2\RSS\my_trigger.py", line 16, in check_update
    await rss_parsing.start(rss)
  File "src/plugins\ELF_RSS2\RSS\rss_parsing.py", line 152, in start
    item_msg += await handle_summary(summary=item['summary'], rss=rss)
  File "src/plugins\ELF_RSS2\RSS\rss_parsing.py", line 336, in handle_summary
    res_msg += await handle_img(html=summary_html, img_proxy=rss.img_proxy, img_
num=rss.max_image_number)
  File "src/plugins\ELF_RSS2\RSS\rss_parsing.py", line 525, in handle_img
    img_base64 = await download_image(img.attr("src"), img_proxy)
  File "src/plugins\ELF_RSS2\RSS\rss_parsing.py", line 506, in download_image
    if pic.STATUS_CODE not in STATUS_CODE:
AttributeError: 'Response' object has no attribute 'STATUS_CODE'

**Comment by NekoAria** [comment]
https://github.com/Quan666/ELF_RSS/blob/04a89a293c48df84dceae0adb86fd33197424510/src/plugins/ELF_RSS2/RSS/rss_parsing.py#L505-L508

是这个提交的问题，在下一个提交里就被修正了。
如果你不是特别急着用新功能的话，等下一个版本吧。
之前是积压了太多提交没发布新版本，结果没经过测试就发布了。

**Comment by Quan666** [comment]
https://github.com/Quan666/ELF_RSS/releases/tag/v2.2.2-fix
